### ISSUE TITLE
U4-3805

### ISSUE THREAD

**Issue by leekelleher** [abjerner/Our.Umbraco.Preflight#1]
@abjerner You may want to add a comment on the Umbraco issue tracker about your project and/or the code you've written so far...

http://issues.umbraco.org/issue/U4-3805

I'd hate to see you duplicate or waste efforts. Unless you have plans for a separate/standalone package?

**Comment by abjerner** [comment]
I have answered on the issue tracker ;)

The thought was to create a community project with the potential of donating the code to the core.

**Comment by leekelleher** [comment]
:+1: Cool.
